# Generated by Django 2.1.7 on 2019-03-05 20:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=255)),
                ('NfDeOrigem', models.CharField(max_length=5)),
                ('NfDeEntrada', models.PositiveIntegerField()),
                ('NfDeSAida', models.PositiveIntegerField()),
                ('efeito', models.PositiveIntegerField()),
                ('NumeroConserto', models.PositiveIntegerField()),
                ('endedor', models.CharField(max_length=255)),
                ('transpotadora', models.CharField(max_length=255)),
                ('CustoColeta', models.DecimalField(decimal_places=2, max_digits=8)),
                ('CustoIda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('CustoVenda', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
